# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20160705_2004'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='archiveunits',
            table='app_archiveunits',
        ),
        migrations.AlterModelTable(
            name='archiveunittypes',
            table='app_archiveunittypes',
        ),
        migrations.AlterModelTable(
            name='boxes',
            table='app_boxes',
        ),
        migrations.AlterModelTable(
            name='clientrequests',
            table='app_clientrequests',
        ),
        migrations.AlterModelTable(
            name='clients',
            table='app_clients',
        ),
        migrations.AlterModelTable(
            name='criteria',
            table='app_criteria',
        ),
        migrations.AlterModelTable(
            name='criteriatypes',
            table='app_criteriatypes',
        ),
        migrations.AlterModelTable(
            name='delivertypes',
            table='app_delivertypes',
        ),
        migrations.AlterModelTable(
            name='locations',
            table='app_locations',
        ),
        migrations.AlterModelTable(
            name='places',
            table='app_places',
        ),
        migrations.AlterModelTable(
            name='projects',
            table='app_projects',
        ),
        migrations.AlterModelTable(
            name='racks',
            table='app_racks',
        ),
        migrations.AlterModelTable(
            name='requestdatabases',
            table='app_requestdatabases',
        ),
        migrations.AlterModelTable(
            name='requesttypes',
            table='app_requesttypes',
        ),
        migrations.AlterModelTable(
            name='usersinfo',
            table='app_usersinfo',
        ),
    ]
